spring.datasource.url=jdbc:postgresql://localhost:5432/event_db
spring.datasource.username=postgres
spring.datasource.password=4435
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Apenas valida o schema, sem apagar dados
spring.jpa.hibernate.ddl-auto=validate